[package]
name    = "chb4"
version = "0.1.0"
authors = ["Chronophylos <nikolai@chronophylos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitchchat        = "0.8"
log               = "0.4"
yansi             = "0.5"
flexi_logger      = "0.14"
config            = "0.10"
tokio             = { version = "0.2", default-features = false, features = ["full"] }
diesel            = { version = "1.0", default-features = false, features = ["mysql", "chrono"] }
diesel_migrations = "1.4"
chrono            = "0.4"
