[package]
name    = "chb4"
version = "0.1.0"
authors = ["Chronophylos <nikolai@chronophylos.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort' # abort on panic instead of unwinding

[dependencies]
bytes             = { version = "0.5", features = ["serde"] }
chrono            = "0.4"
config            = { version = "0.10", default-features = false, features = ["toml"] }
diesel            = { version = "1.0", default-features = false, features = ["mysql", "chrono", "r2d2"] }
diesel_migrations = "1.4"
flexi_logger      = "0.14"
futures-util      = "0.3"
hyper             = "0.13"
log               = "0.4"
rand              = { version = "0.7", features = ["log"] }
regex             = "1"
serde_json        = "1.0"
serde             = { version = "1.0", features = ["derive"] }
simple-error      = "0.2"
tokio             = { version = "0.2", default-features = false, features = ["macros"] }
twitchchat        = "0.8"
yansi             = "0.5"
