[package]
name    = "chb4"
version = "0.1.0"
authors = ["Chronophylos <nikolai@chronophylos.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort' # abort on panic instead of unwinding

[dependencies]
twitchchat        = "0.8"
log               = "0.4"
yansi             = "0.5"
flexi_logger      = "0.14"
config            = { version = "0.10", default-features = false, features = ["toml"] }
tokio             = { version = "0.2", default-features = false, features = ["macros"] }
diesel            = { version = "1.0", default-features = false, features = ["mysql", "chrono"] }
diesel_migrations = "1.4"
chrono            = "0.4"
regex             = "1"
rand              = { version = "0.7", features = ["log"] }
